# Generated by Django 3.1 on 2020-08-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
