# Generated by Django 3.1 on 2020-08-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200819_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Sconditions',
            new_name='Soil_conditions',
        ),
        migrations.AddField(
            model_name='product',
            name='Form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
