# Generated by Django 3.1 on 2020-08-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200819_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Soil_conditions',
            new_name='Soil_Conditions',
        ),
    ]
